name: http_logger
description: A logging middleware for Dart's http module.
version: 1.0.0
author: Gurleen Sethi <sarusethi@rocketmail.com>
homepage: http://www.github.com/gurleensethi

dependencies:
  http_middleware:
    git:
      url: git://github.com/pavelhouzva/http_middleware.git
      ref: master

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
